# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ca1640218c1adb44f8f735f44c1bf05bd58eb6f4ab7da52339444a711f20cdbf064b5696490920f94a7bf803ff0984fdedf5a2b4c2bbdfdb86d6049ab5fa626

test:
  secret_key_base: fba1b211e0660afc2c722a8bbb4e3ff19d534eb912c4e9ceeb0cc3a4b7a19dbb2eb9ce4a1505e9c38f4ef1eb247405b0d7ad97212178571c839ec3b5e5f10f76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
